// RESTAURANTS
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';

// MODALS
export const OPEN_CREATE_RESTAURANT_MODAL = 'OPEN_CREATE_RESTAURANT_MODAL';
export const CLOSE_CREATE_RESTAURANT_MODAL = 'CLOSE_CREATE_RESTAURANT_MODAL';

// STAFF
export const ADD_STAFF_MEMBER = 'ADD_STAFF_MEMBER';
export const FETCH_STAFF = 'FETCH_STAFF';
export const UPDATE_STAFF_MEMBER = 'UPDATE_STAFF_MEMBER';
export const REMOVE_STAFF_MEMBER = 'REMOVE_STAFF_MEMBER';
