//ENTITIES
export const RECEIVE_ENTITIES = 'RECEIVE_ENTITIES';
export const REMOVE_ENTITY = 'REMOVE_ENTITY';

// RESTAURANTS
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_RESTAURANT = 'FETCH_RESTAURANT';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const OPEN_CREATE_RESTAURANT_MODAL = 'OPEN_CREATE_RESTAURANT_MODAL';
export const CLOSE_CREATE_RESTAURANT_MODAL = 'CLOSE_CREATE_RESTAURANT_MODAL';

// STAFF
export const UNAUTH_MEMBER        = 'UNAUTH_MEMBER';
export const ADD_STAFF_MEMBER     = 'ADD_STAFF_MEMBER';
export const FETCH_STAFF          = 'FETCH_STAFF';
export const UPDATE_STAFF_MEMBER  = 'UPDATE_STAFF_MEMBER';
export const REMOVE_STAFF_MEMBER  = 'REMOVE_STAFF_MEMBER';

export const OPEN_STAFF_MODAL     = 'OPEN_STAFF_MODAL';
export const CLOSE_STAFF_MODAL    = 'CLOSE_STAFF_MODAL';
export const SELECT_MEMBER_TO_EDIT    = 'SELECT_MEMBER_TO_EDIT';

// STAFF MEMBER

export const AUTH_MEMBER            = 'AUTH_MEMBER';
export const FETCHING_MEMBER        = 'FETCHING_MEMBER';
export const FETCH_MEMBER_SUCCESS   = 'FETCH_MEMBER_SUCCESS';

// TABLES
export const ADD_TABLE              = 'ADD_TABLE';
export const FETCH_TABLES           = 'FETCH_TABLES';
export const UPDATE_TABLE           = 'UPDATE_TABLE';
export const REMOVE_TABLE           = 'REMOVE_TABLE';

export const OPEN_TABLES_MODAL      = 'OPEN_TABLES_MODAL';
export const CLOSE_TABLES_MODAL     = 'CLOSE_TABLES_MODAL';
export const SELECT_TABLE_TO_EDIT   = 'SELECT_TABLE_TO_EDIT';

// CATEGORIES
export const ADD_CATEGORY              = 'ADD_CATEGORY';
export const FETCH_CATEGORIES          = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED';
export const UPDATE_CATEGORY           = 'UPDATE_CATEGORY';
export const REMOVE_CATEGORY           = 'REMOVE_CATEGORY';

export const OPEN_CATEGORIES_MODAL      = 'OPEN_CATEGORIES_MODAL';
export const CLOSE_CATEGORIES_MODAL     = 'CLOSE_CATEGORIES_MODAL';
export const SELECT_CATEGORY_TO_EDIT    = 'SELECT_CATEGORY_TO_EDIT';

// INREDIENTS
export const ADD_INGREDIENT              = 'ADD_INGREDIENT';
export const FETCH_INGREDIENTS          = 'FETCH_INGREDIENTS';
export const FETCH_INGREDIENTS_FULFILLED = 'FETCH_INGREDIENTS_FULFILLED';
export const UPDATE_INGREDIENT           = 'UPDATE_INGREDIENT';
export const REMOVE_INGREDIENT           = 'REMOVE_INGREDIENT';

export const OPEN_INGREDIENTS_MODAL      = 'OPEN_INGREDIENTS_MODAL';
export const CLOSE_INGREDIENTS_MODAL     = 'CLOSE_INGREDIENTS_MODAL';
export const SELECT_INGREDIENT_TO_EDIT    = 'SELECT_INGREDIENT_TO_EDIT';

// INREDIENTS
export const ADD_DISH               = 'ADD_DISH';
export const FETCH_DISHES           = 'FETCH_DISHES';
export const FETCH_DISHES_FULFILLED = 'FETCH_DISHES_FULFILLED';
export const UPDATE_DISH            = 'UPDATE_DISH';
export const REMOVE_DISH            = 'REMOVE_DISH';

export const OPEN_DISHES_MODAL      = 'OPEN_DISHES_MODAL';
export const CLOSE_DISHES_MODAL     = 'CLOSE_DISHES_MODAL';
export const SELECT_DISH_TO_EDIT    = 'SELECT_DISH_TO_EDIT';

// ORDERS
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const SET_SELECTED_ORDER = 'SET_SELECTED_ORDER';


//LOGGER
export const CLOSE_LOGGER = 'CLOSE_LOGGER';
