// RESTAURANTS
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const OPEN_CREATE_RESTAURANT_MODAL = 'OPEN_CREATE_RESTAURANT_MODAL';
export const CLOSE_CREATE_RESTAURANT_MODAL = 'CLOSE_CREATE_RESTAURANT_MODAL';

// STAFF
export const ADD_STAFF_MEMBER     = 'ADD_STAFF_MEMBER';
export const FETCH_STAFF          = 'FETCH_STAFF';
export const UPDATE_STAFF_MEMBER  = 'UPDATE_STAFF_MEMBER';
export const REMOVE_STAFF_MEMBER  = 'REMOVE_STAFF_MEMBER';

export const OPEN_STAFF_MODAL     = 'OPEN_STAFF_MODAL';
export const CLOSE_STAFF_MODAL    = 'CLOSE_STAFF_MODAL';
export const SELECT_MEMBER_TO_EDIT    = 'SELECT_MEMBER_TO_EDIT';

// TABLES
export const ADD_TABLE              = 'ADD_TABLE';
export const FETCH_TABLES           = 'FETCH_TABLES';
export const UPDATE_TABLE           = 'UPDATE_TABLE';
export const REMOVE_TABLE           = 'REMOVE_TABLE';

export const OPEN_TABLES_MODAL      = 'OPEN_TABLES_MODAL';
export const CLOSE_TABLES_MODAL     = 'CLOSE_TABLES_MODAL';
export const SELECT_TABLE_TO_EDIT   = 'SELECT_TABLE_TO_EDIT';
